[project]
name = "x"
version = "0.1.0"
description = "Utility CLI for interacting with Advent of Code"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "junitparser>=4.0.2",
    "py-markdown-table>=1.3.0",
]
