[future-incompat-report]
frequency = "always"

[profile.release]
codegen-units = 1
lto           = "fat"

[profile.profiling]
debug    = true
inherits = "release"

[profile.fast-test]
debug-assertions = true
inherits         = "profiling"
lto              = "thin"
overflow-checks  = true
