[future-incompat-report]
frequency = "always"

[profile.release]
codegen-units = 1
lto           = "fat"

[profile.profiling]
debug    = true
inherits = "release"

[profile.fast-test]
codegen-units = 8
incremental   = true
inherits      = "test"
opt-level     = 3
