[package]
edition.workspace = true
license.workspace = true
name              = "aoc-common"
version.workspace = true

[dependencies]
either.workspace    = true
itertools.workspace = true
rayon.workspace     = true
